### ISSUE TITLE
Boundary datastore needed when using global DT data only?

### ISSUE THREAD

**Issue by ealerskans** [ealerskans/mlwm-deployment#4]
The neural-lam config for the trained model contains a link to a `datastore_boundary`  config file. However, when doing the prediction we only want to use the global DT data. How does this fit in with the trained model using a `datastore_boundary`? Do we need to add such a datastore config as well? This would then also include global DT data? 

```
datastore:
  kind: mdp
  config_path: /dcai/projects/cu_0003/user_space/hinkas/git-repos/ablation-studies/configs/danra_model1/danra_model1_config.yaml
datastore_boundary:
  kind: mdp
  config_path: /dcai/projects/cu_0003/user_space/hinkas/git-repos/ablation-studies/configs/era_forcing/era_7deg_model1_config.yaml
training:
  state_feature_weighting:
    __config_class__: ManualStateFeatureWeighting
    weights:
      ...
  output_clamping:
    lower:
      ...
    upper:
      ...
  excluded_intervals:
    - ["2002-11-19T00", "2002-11-19T06"]
    - ["2007-08-26T00", "2007-08-26T21"]
    - ["2017-11-25T15", "2017-11-25T15"]
```
